services:
  - type: web
    name: careway-frontend
    plan: free
    runtime: docker
    region: frankfurt
    envVars:
      - key: VITE_API_URL
        value: https://careway-backend.onrender.com
      - key: NODE_ENV
        value: production
